sudo: required

language: bash
services: docker

env:
 - VERSION=snapshot
 - VERSION=4.1
 - VERSION=4.0
 - VERSION=3.4
 - VERSION=3.3
 - VERSION=3.2
 - VERSION=3.1
 - VERSION=3.0
 - VERSION=2.8


before_script:
  - docker version
  - image="ffmpeg:${VERSION}"

script:
  - docker build -t "${image}" --build-arg MAKEFLAGS="-j$(($(grep -c ^processor /proc/cpuinfo) + 1))" docker-images/${VERSION}/
  - docker run --rm ${image} -buildconf

after_script:
  - docker images
# vim:set et ts=2 sw=2:
